services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: agenda_db
    networks:
      - postgres-compose-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "15432:80"
    networks:
      - postgres-compose-network


networks:
  postgres-compose-network:
    driver: bridge